//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockVoice.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockVoice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Symbol&quot;,&quot;Name&quot;,&quot;LastSale&quot;,&quot;MarketCap&quot;,&quot;ADR TSO&quot;,&quot;IPOyear&quot;,&quot;Sector&quot;,&quot;Industry&quot;,&quot;Summary Quote&quot;,
        ///&quot;PIH&quot;,&quot;1347 Property Insurance Holdings, Inc.&quot;,&quot;7.15&quot;,&quot;42590876.9&quot;,&quot;n/a&quot;,&quot;2014&quot;,&quot;Finance&quot;,&quot;Property-Casualty Insurers&quot;,&quot;http://www.nasdaq.com/symbol/pih&quot;,
        ///&quot;TURN&quot;,&quot;180 Degree Capital Corp.&quot;,&quot;1.68&quot;,&quot;52284224.16&quot;,&quot;n/a&quot;,&quot;n/a&quot;,&quot;Finance&quot;,&quot;Finance/Investors Services&quot;,&quot;http://www.nasdaq.com/symbol/turn&quot;,
        ///&quot;FLWS&quot;,&quot;1-800 FLOWERS.COM, Inc.&quot;,&quot;10.75&quot;,&quot;704867373.5&quot;,&quot;n/a&quot;,&quot;1999&quot;,&quot;Consumer Services&quot;,&quot;Other Specialty Stores&quot;,&quot;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string companylist {
            get {
                return ResourceManager.GetString("companylist", resourceCulture);
            }
        }
    }
}
